# **what?**
#
# Inputs:
#   
# **why?**
#
# **when?**
#

name: Check if the build exists

on:
  workflow_call:

permissions:
  issues: write

jobs:
  build-exists:
    runs-on: ubuntu-latest
    # if: |    TODO: is it conditional?
    #   ((github.event.action == 'opened') || 
    #   (github.event.action == 'labeled' && github.event.label.name == 'jira'))
    # outputs:   TODO: are outputs needed?
    #   issueId: ${{ steps.save-id.outputs.issueId }}
  
    steps:
      - name: Placeholder
        run: echo Workflow is not built
      - name: Set output
        run: echo '::set-output name=exists::"true"'