name: "Publish to PyPI"
description: "Publish artifacts from an archive to PyPI"

inputs:
    archive-name:
        description: "Name of the archive containing the artifacts, leave blank if local"
        default: ""
    index-url:
        description: "The url for the PyPI index"
        required: true

runs:
    using: composite
    steps:
    -   name: "[DEBUG] Inputs"
        shell: bash
        run: |
            echo archive-name : ${{ inputs.archive-name }}
            echo index-url    : ${{ inputs.index-url }}

    -   name: "Download artifacts from `${{ inputs.archive-name }}`"
        if: ${{ !(inputs.archive-name == '') }}
        uses: actions/download-artifact@v4
        with:
            name: ${{ inputs.archive-name }}
            path: dist/

    -   name: "[INFO] Downloaded artifacts"
        if: ${{ !(inputs.archive-name == '') }}
        shell: bash
        run: |
            echo "::notice title=$TITLE::$MESSAGE"
        env:
            TITLE: "[${{ env.NOTIFICATION_PREFIX }}]: Downloaded artifacts"
            MESSAGE: "Downloaded artifacts from ${{ inputs.archive-name }}"

    -   name: "[DEBUG] Found artifacts"
        shell: bash
        run: echo $(ls ./dist)

    -   name: "Publish artifacts to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            repository-url: ${{ inputs.index-url }}
            packages-dir: dist/

    -   name: "[INFO] Published artifacts to PyPI"
        shell: bash
        run: |
            echo "::notice title=$TITLE::$MESSAGE"
        env:
            TITLE: "[${{ env.NOTIFICATION_PREFIX }}]: Published artifacts to PyPI"
            MESSAGE: $(ls ./dist)
