name: 'Prepare, Build and Release to GitHub and Pypi'

description: 'Generate changelog with changie, bump version, build artifacts and finally release ot GitHub and Pypi'

inputs:
  sha:
    description: 'The commit sha to release'
    required: true
  version_number:
    description: 'The release version number (ie. 1.0.0b1)'
    default: '2.2.2'  # TODO: remove when done testing!
    required: true
  target_branch:
    description: 'Target branch to release from (ie. 1.1.latest)'
    default: '2.2.latest'  # TODO: remove when done testing!
    required: true
  build_script_path:
    description: 'Target branch to release from (ie. 1.1.latest)'
    default: scripts/build-dist.sh
    required: true
  s3_bucket_name:
    description: 'Target branch to release from (ie. 1.1.latest)'
    default: core-team-artifacts
    required: true
  package_test_command:
    description: 'Target branch to release from (ie. 1.1.latest)'
    default: pip freeze  # TODO: change to dbt --version
    required: true
  is_prod:
    # TODO: need an action to clean up test builds for testing purposes
    description: 'Is this a production build/release?'
    required: true
  AWS_ACCESS_KEY_ID:
    # TODO: need an action to clean up test builds for testing purposes
    description: 'S3 access key id'
    required: true
  AWS_SECRET_ACCESS_KEY:
    # TODO: need an action to clean up test builds for testing purposes
    description: 'S3 access key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: release_prep
      uses: dbt-labs/actions/.github/workflows/_release-prep.yml@er/release
      with:
        sha: ${{ github.event.inputs.sha }}
        version_number: ${{ github.event.inputs.version_number }}
        target_branch: ${{ github.event.inputs.target_branch }}

    - name: build
      uses: dbt-labs/actions/.github/workflows/_build.yml@er/release
      with:
        # notice this is the sha from the last job so to include the version bump / changelog
        sha: ${{ steps.release_prep.outputs.final_sha }}
        version_number: ${{ inputs.version_number }}
        changelog_path: ${{ steps.release_prep.outputs.changelog_path }}
        build_script_path: ${{ inputs.build_script_path }}
        s3_bucket_name: ${{ inputs.s3_bucket_name }}
        package_test_command: ${{ inputs.package_test_command }}
        AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACT_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACT_AWS_SECRET_ACCESS_KEY }}

    - name: github_release
      uses: dbt-labs/actions/.github/workflows/_github-release.yml@er/release
      with:
        sha: ${{ steps.release_prep.outputs.final_sha }}
        version_number: ${{ inputs.version_number }}
        changelog_path: ${{ steps.release_prep.outputs.changelog_path }}
        # TODO: pass these file paths
        file_uploads: |
          test_github_actions-${{github.event.inputs.version_number}}-py3-none-any.whl
          test-github-actions-${{github.event.inputs.version_number}}.tar.gz

    # this is still WIP
    # - name: pypi_release:
    #   needs: [github_release]
    #   uses: dbt-labs/actions/.github/workflows/_pypi-release.yml@er/release
    #   with:
    #     tag: ${{ steps.github_release.outputs.tag }}
    #     is_prod: ${{ github.event.inputs.is_prod }}