version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/scripts/core-triage"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
  - package-ecosystem: "docker"
    directory: "/fetch-container-tags"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
  - package-ecosystem: "docker"
    directory: "/fetch-repo-branches"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
  - package-ecosystem: "docker"
    directory: "/parse-semver"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
  - package-ecosystem: "docker"
    directory: "/py-package-info"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
