name: "Commit and create pull request"
description: "Commit local changes and create a pull request"

inputs:
  message:
    description: "The commit message"
    required: true
  title:
    description: "The title for the pull request"
    required: true
  body:
    description: "The body for the pull request"
    required: true
  target:
    description: "The branch to merge into"
    default: "main"

runs:
  using: composite
  steps:
    - name: "Commit local changes"
      id: commit
      if: ${{ steps.updates.outputs.results }}
      shell: bash
      run: |
        user="Github Build Bot"
        email="buildbot@fishtownanalytics.com"
        git config user.name "$user"
        git config user.email "$email"
        git status
        git add .
        git commit -m "${{ inputs.message }}"

    - name: "Get current branch"
      id: current_branch
      shell: bash
      run: |
        name=$(git rev-parse --abbrev-ref HEAD)
        echo "name=$name" >> $GITHUB_OUTPUT

    - name: "Open pull request"
      id: pull_request
      shell: bash
      run: |
        url=$(gh pr create \
          -B ${{ inputs.target }} \
          -H ${{ steps.current_branch.outputs.name }} \
          -t "${{ inputs.title }}" \
          -b "${{ inputs.body }}" \
        )
        echo "url=$url" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ secrets.FISHTOWN_BOT_PAT }}

    - name: "[Notification] Pull request opened"
      shell: bash
      run: |
        message="PR opened at ${{ steps.pull_request.outputs.url }}"
        echo "::notice title="Pull request opened": $title::$message"
