name: "Audit GitHub commit"
description: "Get metadata about a GitHub commit"

inputs:
    sha:
        description: "The commit to audit"
        required: true
    release-search-limit:
        description: "The number of releases to search through"
        default: "15"

outputs:
    tag:
        description: "The associated release tag, if the release exists"
        value: ${{ steps.commit.outputs.tag_name }}
    release-id:
        description: "The associated release id, if the release exists"
        value: ${{ steps.commit.outputs.id }}
    pre-release:
        description: "If the associated release exists, is it a pre-release?"
        value: ${{ steps.commit.outputs.prerelease }}
    commitish:
        description: "The associated commitish, if the release exists"
        value: ${{ steps.commit.outputs.target_commitish }}

runs:
    using: composite
    steps:
    -   name: "[DEBUG] Inputs"
        shell: bash
        run: |
            echo sha : ${{ inputs.sha }}

    -   name: "Check if a release exists for `${{ inputs.sha }}`"
        id: commit
        uses: cardinalby/git-get-release-action@1.2.4
        with:
            commitSha: ${{ inputs.sha }}
            doNotFailIfNotFound: true  # return blank outputs when not found instead of error
            searchLimit: ${{ fromJSON(inputs.release-search-limit) }}
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    -   name: "[DEBUG] Commit metadata"
        shell: bash
        run: |
            echo sha         : ${{ inputs.sha }}
            echo tag         : ${{ steps.commit.outputs.tag_name }}
            echo release-id  : ${{ steps.commit.outputs.id }}
            echo pre-release : ${{ steps.commit.outputs.prerelease }}
            echo commitish   : ${{ steps.commit.outputs.target_commitish }}
