name: "GitHub commit create"
description: "Commit changes into the current branch, push back to the remote, and return the resulting SHA"

inputs:
    message:
        description: "The commit message"
        required: true
    user:
        description: "The user for the commit"
        default: "Github Build Bot"
    email:
        description: "The email for the commit"
        default: "buildbot@fishtownanalytics.com"

outputs:
    sha:
        description: "The SHA for the commit"
        value: ${{ steps.commit.outputs.sha }}

runs:
    using: composite
    steps:
    -   name: "[DEBUG] Inputs"
        shell: bash
        run: |
            echo "==========INPUTS=========="
            echo message : ${{ inputs.message }}
            echo user    : ${{ inputs.user }}
            echo email   : ${{ inputs.email }}

    -   name: "Commit and push changes"
        id: commit
        shell: bash
        run: |
            git config user.name "$USER"
            git config user.email "$EMAIL"
            git pull
            git add .
            git commit -m "$MESSAGE"
            git push
            echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        env:
            USER: ${{ inputs.user }}
            EMAIL: ${{ inputs.email }}
            MESSAGE: [automated] ${{ inputs.message }}

    -   name: "[DEBUG] Outputs"
        shell: bash
        run: |
            echo "==========OUTPUTS=========="
            echo sha : ${{ steps.commit.outputs.sha }}

    -   name: "[INFO] GitHub commit create"
        shell: bash
        run: echo "::notice title=$TITLE::$MESSAGE"
        env:
            TITLE: "[${{ env.NOTIFICATION_PREFIX }}] GitHub commit create"
            MESSAGE: "Committed and pushed changes back to the remote repository with SHA `${{ steps.commit.outputs.sha }}`"
