name: "Publish GitHub draft release as full release"
description: "Publish an existing draft release as a non-draft release"

inputs:
    tag:
        description: "The tag to publish (i.e. v1.0.0b1)"
        required: true

runs:
    using: composite
    steps:
    -   name: "[DEBUG] Inputs"
        shell: bash
        run: |
            echo tag : ${{ inputs.tag }}

    -   name: "Publish draft `${{ inputs.tag }}` as full release"
        shell: bash
        run: gh release edit $TAG --repo $REPO --draft=false
        env:
            TAG: ${{ inputs.tag }}
            REPO: "https://github.com/dbt-labs/${{ github.repository }}"
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    -   name: "[INFO] Published draft as full release"
        shell: bash
        run: |
            echo "::notice title=$TITLE::$MESSAGE"
        env:
            TITLE: "[${{ env.NOTIFICATION_PREFIX }}]: Published draft as full release"
            MESSAGE: "tag: `${{ inputs.tag }}`"
