name: "Release to GitHub"
description: "Release to GitHub"
inputs:
  sha:
    description: 'The last commit sha in the release'
    required: true
  version:
    description: 'The release version number (i.e. 1.0.0b1)'
    required: true
  repository:
    description: 'The name of the respoitory to release'
    required: true
# outputs:
#   name:
#     description: "Package name"

runs:
  using: "composite"

  steps:

    - name: Inputs
      uses: dunno bash?
      run: |
          echo The last commit sha in the release: ${{ inputs.sha }}
          echo The release version number: ${{ inputs.version }}
          echo The name of the respoitory to release: ${{ inputs.version }}

    - name: download artifacts
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: '.'

    # Need to set an output variable because env variables can't be taken as input
    # This is needed for the next step with releasing to GitHub
    - name: Find release type
      id: release_type
      uses: dbt-labs/parse-semver
      with:
        version: ${{ inputs.version }}

    - name: Creating GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ repository }} v${{inputs.version_number}}
        tag_name: v${{inputs.version_number}}
        prerelease: ${{steps.release_type.outputs.is-pre-release }}
        target_commitish: ${{inputs.sha}}
        body_path: ${{ github.workspace }}/.changes/${{steps.release_type.outputs.semver-compliant-version }}.md
        # note you'll typically need to create a personal access token
        # with permissions to create releases in the other repo
        # token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        files: |
          dbt_postgres-${{github.event.inputs.version_number}}-py3-none-any.whl
          dbt_core-${{github.event.inputs.version_number}}-py3-none-any.whl
          dbt-postgres-${{github.event.inputs.version_number}}.tar.gz
          dbt-core-${{github.event.inputs.version_number}}.tar.gz
        env:
          GITHUB_REPOSITORY: dbt-labs/${{ repository }}
