name: "Build and Release"

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'The last commit sha in the release'
        required: true
        type: string
      version_number:
        description: 'The release version number (ie. 1.0.0b1)'
        required: true
        type: string
      build_script_path:
        description: 'The path to the build script(default: ./scripts/build-dist.sh))'
        default: 'scripts/build-dist.sh'
        required: true
        type: string
      is_prod:
        # TODO: need an action to clean up test builds for testing purposes
        description: 'Is this a production build/release'
        default: false
        required: true
        type: boolean
    # outputs:
    #   name:
        # description: "Package name"

# TODO: validate
permissions:
  contents: write

jobs:

  build:
    uses: dbt-labs/actions/.github/workflows/_build.yml@er/release
    with:
      sha: ${{ github.event.inputs.sha }}
      version_number: ${{ github.event.inputs.version_number }}
      build_script_path: ${{ github.event.inputs.build_script_path }}
      package_test_command: "pip freeze"  # this should not be input at this level, defaults to `dbt --version``

  github_release:
    needs: [build]
    uses: dbt-labs/actions/.github/workflows/_github-release.yml@er/release
    with:
      sha: ${{ github.event.inputs.sha }}
      version_number: ${{ github.event.inputs.version_number }}
      file_uploads: |
        action_testing-${{github.event.inputs.version_number}}-py3-none-any.whl
        action_testing-${{github.event.inputs.version_number}}.tar.gz

  # pypi_release:
  #   needs: [github_release]
  #   uses: dbt-labs/actions/.github/workflows/_pypi-release.yml@er/release
  #   with:
  #     is_prod: ${{ github.event.inputs.is_prod }}