name: "Build and Release"

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'The last commit sha in the release'
        required: true
        type: string
      version_number:
        description: 'The release version number (ie. 1.0.0b1)'
        required: true
        type: string
      is_prod:
        # TODO: need an action to clean up test builds for testing purposes
        description: 'Is this a production build/release'
        default: false
        required: true
        type: boolean

permissions:
  contents: write

jobs:

  build:
    uses: dbt-labs/actions/.github/workflows/_build.yml@er/release  # TODO: This should be a tag
    with:
      sha: ${{ github.event.inputs.sha }}
      version_number: ${{ github.event.inputs.version_number }}
      # the following values should be the same for all runs in a repository so do not need to be input
      build_script_path: scripts/build-dist.sh
      s3_bucket: core-team-artifacts
      package_test_command: dbt --version

  github_release:
    needs: [build]
    uses: dbt-labs/actions/.github/workflows/_github-release.yml@er/release  # TODO: This should be a tag
    with:
      sha: ${{ github.event.inputs.sha }}
      version_number: ${{ github.event.inputs.version_number }}
      file_uploads: |
        test-github-actions-${{github.event.inputs.version_number}}-py3-none-any.whl
        test-github-actions-${{github.event.inputs.version_number}}.tar.gz

  # this is still WIP
  # pypi_release:
  #   needs: [github_release]
  #   uses: dbt-labs/actions/.github/workflows/_pypi-release.yml@er/release
  #   with:
  #     is_prod: ${{ github.event.inputs.is_prod }}
