name: "Setup environment"
description: "Setup a python environment with `hatch`, `pip`, and `changie` installed"

inputs:
    python-version:
        description: "The version of python to install"
        default: "3.8"

runs:
    using: composite
    steps:
    -   name: "[DEBUG] Inputs"
        shell: bash
        run: |
            echo "==========INPUTS=========="
            echo python-version : ${{ inputs.python-version }}

    -   name: "Install 'python${{ inputs.python-version }}`"
        uses: actions/setup-python@v5
        with:
            python-version: ${{ inputs.python-version }}

    -   name: "Install `hatch`"
        shell: bash
        run: python -m pip install --upgrade pip hatch

    -   name: "Install `changie`"
        shell: bash
        run: |
            export PATH=$PATH:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin
            brew tap miniscruff/changie https://github.com/miniscruff/changie
            brew install changie

    -   name: "[DEBUG] Outputs"
        shell: bash
        run: |
            echo "==========OUTPUTS=========="
            echo "N/A"
