name: "GitHub team get"
description: "Get metadata about a GitHub team"

inputs:
    team:
        description: "The name of the team"
        required: true

outputs:
    members:
        description: "A space delimited list of team members"
        value: ${{ steps.members.outputs.members }}

runs:
    using: composite
    steps:
    -   name: "[DEBUG] Inputs"
        shell: bash
        run: |
            echo "==========INPUTS=========="
            echo team : ${{ inputs.team }}

    -   name: "Create output file name"
        shell: bash
        run: echo "OUTPUT_FILE=output_$GITHUB_RUN_ID.json" >> $GITHUB_ENV

    -   name: "Get team membership"
        shell: bash
        run: gh api $ENDPOINT -H "$HEADER" > $OUTPUT_FILE
        env:
            ENDPOINT: "orgs/dbt-labs/teams/${{ inputs.team }}/members"
            HEADER: "Accept: application/vnd.github+json"
            GH_TOKEN: ${{ secrets.IT_TEAM_MEMBERSHIP }}

    -   name: "Parse team membership"
        id: members
        shell: bash
        run: |
            team_list=$(jq -r '.[].login' $OUTPUT_FILE)
            team_list_single=$(echo $team_list | tr '\n' ' ')
            echo "members=$team_list_single" >> $GITHUB_OUTPUT
            rm $OUTPUT_FILE

    -   name: "[DEBUG] Outputs"
        shell: bash
        run: |
            echo "==========OUTPUTS=========="
            echo members      : ${{ steps.members.outputs.members }}
