name: "Edit GitHub release"
description: "Update a GitHub release with the provided attributes"

inputs:
    tag:
        description: "The tag to publish (i.e. v1.0.0b1)"
        required: true
    is-draft:
        description: "Indicates that this is a draft release"
        default: ""

runs:
    using: composite
    steps:
    -   name: "[DEBUG] Inputs"
        shell: bash
        run: |
            echo "==========INPUTS=========="
            echo tag      : ${{ inputs.tag }}
            echo is-draft : ${{ inputs.is-draft }}

    -   name: "Set release inputs"
        if: ${{ inputs.is-draft != '' }}
        id: release
        shell: bash
        run: ./github/release/edit/set_release_inputs.sh
        env:
            IS_DRAFT: ${{ fromJSON(inputs.is-draft) }}

    -   name: "Update `${{ inputs.tag }}`"
        shell: bash
        run: gh release edit $TAG --repo $REPO $DRAFT
        env:
            TAG: ${{ inputs.tag }}
            REPO: "https://github.com/dbt-labs/${{ github.repository }}"
            DRAFT: ${{ steps.release.outputs.draft }}
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    -   name: "[INFO] Edit GitHub release"
        shell: bash
        run: echo "::notice title=$TITLE::$MESSAGE"
        env:
            TITLE: "[${{ env.NOTIFICATION_PREFIX }}]: Edit GitHub release"
            MESSAGE: "tag: `${{ inputs.tag }}`"

    -   name: "[DEBUG] Outputs"
        shell: bash
        run: |
            echo "==========OUTPUTS=========="
            echo "N/A"
