name: "Setup environment"
description: "Setup a python environment with `hatch`, `setuptools`, `wheel`, and `changie` installed"

inputs:
    python-version:
        description: "The version of python to install"
        default: "3.8"

runs:
    using: composite
    steps:
    -   name: "[DEBUG] Inputs"
        shell: bash
        run: |
            echo python-version : ${{ inputs.python-version }}

    -   name: "Install 'python${{ inputs.python-version }}`"
        uses: actions/setup-python@v5
        with:
            python-version: ${{ inputs.python-version }}

    -   name: "Install `hatch`, `pip`, `setuptools`, `wheel`"
        shell: bash
        run: python -m pip install --upgrade hatch pip setuptools wheel

    -   name: "Add `linuxbrew` to PATH"
        shell: bash
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

    -   name: "Install `changie`"
        shell: bash
        run: |
            brew tap miniscruff/changie https://github.com/miniscruff/changie
            brew install changie
