# **what?**
#
# Inputs:
#   
# **why?**
#
# **when?**
#

name: Build

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      version_number:
        required: true
        type: string

permissions:
  issues: write

jobs:
  build-packages:
    runs-on: ubuntu-latest
    # if: |    TODO: is it conditional?
    #   ((github.event.action == 'opened') || 
    #   (github.event.action == 'labeled' && github.event.label.name == 'jira'))
    # outputs:   TODO: are outputs needed?
    #   issueId: ${{ steps.save-id.outputs.issueId }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.event.inputs.sha }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: |
          pip install --user --upgrade pip
          pip install --upgrade setuptools wheel twine check-wheel-contents
          pip --version

      - name: Build distributions
        run: ./scripts/build-dist.sh

      - name: Show distributions
        run: ls -lh dist/

      - name: Check distribution descriptions
        run: |
          twine check dist/*

      - name: Check wheel contents
        run: |
          check-wheel-contents dist/*.whl --ignore W007,W008

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/
            !dist/dbt-${{github.event.inputs.version_number}}.tar.gz