name: "Create GitHub release"
description: "Publish release artifacts from an archive to GitHub"

inputs:
    archive-name:
        description: "Name of the archive containing the artifacts, leave blank if local"
        default: ""
    tag:
        description: "The release tag to publish under"
        required: true
    sha:
        description: "Commit SHA being released"
        required: true
    changelog-path:
        description: "Path to the release notes from the repo root"
        required: true
    is-draft:
        description: "Indicates that this is a draft release"
        required: true

runs:
    using: composite
    steps:
    -   name: "[DEBUG] Inputs"
        shell: bash
        run: |
            echo "==========INPUTS=========="
            echo archive-name   : ${{ inputs.archive-name }}
            echo tag            : ${{ inputs.tag }}
            echo sha            : ${{ inputs.sha }}
            echo changelog-path : ${{ inputs.changelog-path }}
            echo is-draft       : ${{ inputs.is-draft }}

    -   name: "Download release artifacts from `${{ inputs.archive-name }}`"
        if: ${{ !(inputs.archive-name == '') }}
        uses: actions/download-artifact@v4
        with:
            name: ${{ inputs.archive-name }}
            path: dist/

    -   name: "[DEBUG] Release artifacts"
        shell: bash
        run: echo $(ls ./dist)

    -   name: "Set release inputs"
        id: release
        shell: bash
        run: ./github/release/create/set_release_inputs.sh
        env:
            IS_PRE_RELEASE: ${{ contains(inputs.tag, 'rc') || contains(inputs.tag, 'b') || contains(inputs.tag, 'a') || contains(inputs.tag, 'dev') }}
            IS_DRAFT: ${{ fromJSON(inputs.is-draft) }}

    -   name: "Publish artifacts to GitHub"
        shell: bash
        run: gh release create $TAG $FILES $DRAFT --notes-file $NOTES_FILE $PRERELEASE --target $TARGET --title "$TITLE" --repo $REPO
        env:
            TAG: ${{ inputs.tag }}
            FILES: "./dist/*"
            DRAFT: ${{ steps.release.output.draft }}
            NOTES_FILE: ${{ inputs.changelog-path }}
            PRERELEASE: ${{ steps.release.output.prerelease }}
            TARGET: ${{ inputs.sha }}
            TITLE: "${{ github.repository }} ${{ inputs.tag }}"
            REPO: "https://github.com/dbt-labs/${{ github.repository }}"
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    -   name: "[INFO] Create GitHub release"
        shell: bash
        run: echo "::notice title=$TITLE::$MESSAGE"
        env:
            TITLE: "[${{ env.NOTIFICATION_PREFIX }}]: Create GitHub release"
            MESSAGE: "tag: `${{ inputs.tag }}` artifacts: `$(ls ./dist)`"

    -   name: "[DEBUG] Outputs"
        shell: bash
        run: |
            echo "==========OUTPUTS=========="
            echo "N/A"
