# **what?**
#
# Inputs:
#   
# **why?**
#
# **when?**
#

name: Build

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      version_number:
        required: true
        type: string
      build_script_path:
        required: true
        type: string

permissions:
  contents: write

jobs:
  check-build-exists:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.set_existence.outputs.exists }}
  
    steps:
      - name: Placeholder
        run: echo Workflow is not built
      - name: Set output
        id: set_existence
        run: echo '::set-output name=exists::"false"'

  build-packages:
    runs-on: ubuntu-latest
    needs: [check-build-exists]
    if: ${{ needs.check-build-exists.exists }} == "false"
    outputs:
      finished: ${{ steps.set_success.outputs.finished }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          # persist-credentials: false  # TODO: with this false I get an error checking it out, it's what existed in previous release version though
          ref: ${{ github.event.inputs.sha }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: |
          pip install --user --upgrade pip
          pip install --upgrade setuptools wheel twine check-wheel-contents
          pip --version

      - name: Build distributions
        run: ./${{ inputs.build_script_path }}

      - name: Show distributions
        run: ls -lh dist/

      - name: Check distribution descriptions
        run: |
          twine check dist/*

      - name: Check wheel contents
        run: |
          check-wheel-contents dist/*.whl --ignore W007,W008

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/
            !dist/dbt-${{ inputs.version_number }}.tar.gz
      
      - name: If we made it here we need to test what we built
        id: set_success
        run: echo '::set-output name=finished::"true"'

  test-build:
    needs: [check-build-exists, build-packages]
    if: ${{ needs.check-build-exists.exists }} == 'false' || ${{ needs.build-packages.finished }} == 'true'
    runs-on: ubuntu-latest
  
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: |
          pip install --user --upgrade pip
          pip install --upgrade wheel
          pip --version

      - uses: actions/download-artifact@v2   # TODO: from S3?
        with:
          name: dist
          path: dist/

      - name: Show distributions
        run: ls -lh dist/

      - name: Install wheel distributions
        run: |
          find ./dist/*.whl -maxdepth 1 -type f | xargs pip install --force-reinstall --find-links=dist/

      - name: Check wheel distributions
        run: |
          dbt --version

      - name: Install source distributions
        run: |
          find ./dist/*.gz -maxdepth 1 -type f | xargs pip install --force-reinstall --find-links=dist/

      - name: Check source distributions
        run: |
          dbt --version