# **what?**
#
# Inputs:
#   
# **why?**
#
# **when?**
#

name: Build

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      version_number:
        required: true
        type: string
      build_script_path:
        required: true
        default: scripts/build-dist.sh
        type: string
      package_test_command:
        required: true
        default: dbt --version
        type: string

permissions:
  contents: write

jobs:
  log-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        run: |
            echo The last commit sha in the release: ${{ github.event.inputs.sha }}
            echo The release version number: ${{ github.event.inputs.version_number }}
            echo The build_script_path: ${{ github.event.inputs.build_script_path }}
            echo The package_test_command: ${{ github.event.inputs.package_test_command }}

  check-build-exists:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.set_existence.outputs.exists }}
  
    steps:
      - name: Placeholder
        run: echo Workflow is not built

      # - maybe use https://github.com/keithweaver/aws-s3-github-action/blob/master/entrypoint.sh
      
      - name: Set output
        id: set_existence
        run: echo '::set-output name=exists::false'

  skip-build:
    runs-on: ubuntu-latest
    needs: [check-build-exists]
    if: needs.check-build-exists.outputs.exists == 'true'

    steps:
      - name: Build Exists, Skip To Test
        run: |
          echo A build already exists for version ${{github.event.inputs.version_number}}, skipping build job

  build-packages:
    runs-on: ubuntu-latest
    needs: [check-build-exists]
    if: needs.check-build-exists.outputs.exists == 'false'

    outputs:
      finished: ${{ steps.set_success.outputs.finished }}

    steps:

      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          # persist-credentials: false  # TODO: with this false I get an error checking it out, it's what existed in previous release version though
          ref: ${{ github.event.inputs.sha }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: |
          pip install --user --upgrade pip
          pip install --upgrade setuptools wheel twine check-wheel-contents
          pip --version

      - name: Build distributions
        run: ./${{ inputs.build_script_path }}

      - name: Show distributions
        run: ls -lh dist/

      - name: Check distribution descriptions
        run: |
          twine check dist/*

      - name: Check wheel contents
        run: |
          check-wheel-contents dist/*.whl --ignore W007,W008

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.version_number }}
          path: |
            dist/
            !dist/dbt-${{ inputs.version_number }}.tar.gz
          if-no-files-found: error

      - name: upload changelog markdown for release notes
        uses: actions/upload-artifact@v2
        # upload the changelog as an artifact for the release notes
        # Would be nice to strip out the formatting on contributors here so that we
          # can leverage GitHubs native contributor recognition
        with:
          name: ${{ github.event.inputs.version_number }}
          path: |
            .changes/${{ github.event.inputs.version_number }}.md
          if-no-files-found: error
      
      - name: If we made it here we need to test what we built
        id: set_success
        run: echo '::set-output name=finished::true'
      
  test-build:
    runs-on: ubuntu-latest
    needs: [check-build-exists, build-packages]
    if: ${{ needs.check-build-exists.outputs.exists }} == false || ${{ needs.build-packages.outputs.finished }} == true
  
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: |
          pip install --user --upgrade pip
          pip install --upgrade wheel
          pip --version

      - uses: actions/download-artifact@v2   # TODO: from S3?
        with:
          name: ${{ github.event.inputs.version_number }}
          path: dist/

      - name: Display structure of all downloaded files
        run: ls -R
      
      - name: Show distributions
        run: ls -lh dist/

      - name: Install wheel distributions
        run: |
          find ./dist/*.whl -maxdepth 1 -type f | xargs pip install --force-reinstall --find-links=dist/

      - name: Check wheel distributions
        run: |
          ${{ github.event.inputs.package_test_command }}

      - name: Install source distributions
        run: |
          find ./dist/*.gz -maxdepth 1 -type f | xargs pip install --force-reinstall --find-links=dist/

      - name: Check source distributions
        run: |
          ${{ github.event.inputs.package_test_command }}
