# **what?**
# Create a new release on GitHub and include any artifacts in the `/dist` directory of the GitHUb artifacts store.
#
# Inputs:
#  sha: the commit to attach to this release
#  version_number: version number for the release (ex: 1.2.3rc2)
#  file_uploads: Newline-delimited globs of paths to assets to upload for release
#   
# **why?**
# Reusable and consistent GitHub release process.
#
# **when?**
# Call after a successful build.  Build artifacts should be ready to release and live in a dist/ directory.
#
# This workflow expects the artifacts to already be built and living in the artifact store of the workflow.
#
# Validation Checks
#
# 1. If no release already exists for this commit and version, create the tag and release it to GitHub.
# 2. If a release already exists for this commit, skip creating the release but finish with a success.
# 3. If a release exists for this commit under a different tag, fail.
# 4. If the commit is already associated with a different release, fail.

name: GitHub Release

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      version_number:
        required: true
        type: string
      changelog_path:
        description: Path to the changelog file for release notes
        required: true
        type: string
      testing: 
        required: true
        type: string
    outputs:
      tag: 
        description: The path to the changelog for this version
        value: ${{ jobs.check-release-exists.outputs.tag }}


permissions:
  contents: write

jobs:
  log-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        run: |
            echo The last commit sha in the release: ${{ inputs.sha }}
            echo The release version number: ${{ inputs.version_number }}
            echo Expected Changlog path: ${{ inputs.changelog_path }}
            echo testing: ${{ inputs.testing }}

  check-release-exists:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.release_check.outputs.exists }}
      draft_exists: ${{ steps.release_check.outputs.draft_exists }}
      tag: ${{ steps.set_tag.outputs.tag }}

    steps:
      - name: Generate Tag in Expected format
        id: set_tag
        run: echo "::set-output name=tag::v${{ inputs.version_number }}"

      - name: Check out the repository
        uses: actions/checkout@v3
      
      # When the GitHub CLI doesn't find a release for the given tag, it will exit 1 with a
      # message of "release not found".  In our case, it's not an actual error, just a 
      # confirmation that the release does not already exists so we can go ahead and create it.
      # The `|| true` makes it so the step does not exit with a non-zero exit code
      - name: Check if release exists for tag
        id: release_check
        run: |
          output=$((gh release view ${{ steps.set_tag.outputs.tag }} --json isDraft,targetCommitish) 2>&1) || true
          if [[ "$output" == "release not found" ]]
          then
            echo Release for tag ${{ steps.set_tag.outputs.tag }} does not exist
            echo "::set-output name=exists::false"
            exit 0
          fi
          commit=$(jq -r '.targetCommitish' <<< "$output")
          if [[ $commit != ${{ inputs.sha }} ]]
          then
            echo Release for tag ${{ steps.set_tag.outputs.tag }} already exists for commit $commit!
            echo Cannot create a new release for commit ${{ inputs.sha }}.  Exiting.
            exit 1
          fi
          isDraft=$(jq -r '.isDraft' <<< "$output")
          if [[ $isDraft -eq true ]] && [[ ${{ inputs.testing }} == "true" ]]
          then
            echo Draft release for tag ${{ steps.set_tag.outputs.tag }} already exists.  Skip GitHub release.
            echo "::set-output name=exists::true"
            echo "::set-output name=draft_exists::false"
          elif [[ $isDraft -eq true ]] && [[ ${{ inputs.testing }} == "false" ]]
          then
            echo Release for tag ${{ steps.set_tag.outputs.tag }} already exists in draft form.  Need to Publish.
            echo "::set-output name=exists::false"
            echo "::set-output name=draft_exists::true"
          else
            echo Release for tag ${{ steps.set_tag.outputs.tag }} already exists.  Skip GitHub release.
            echo "::set-output name=exists::true"
            echo "::set-output name=draft_exists::false"
          fi

          if [[ ${{ inputs.testing }} == "false" ]]
          then
            echo first
          fi
          if [[ ${{ inputs.testing }} -eq "false" ]]
          then
            echo second
          fi
          if [[ ${{ inputs.testing }} == false ]]
          then
            echo third
          fi
          if [[ ${{ inputs.testing }} -eq false ]]
          then
            echo forth
          fi
          if [[ ${{ inputs.testing }} == "true" ]]
          then
            echo fifth
          fi
          if [[ ${{ inputs.testing }} -eq "true" ]]
          then
            echo sixth
          fi
          if [[ ${{ inputs.testing }} == true ]]
          then
            echo seventh
          fi
          if [[ ${{ inputs.testing }} -eq true ]]
          then
            echo eighth
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Log Job Outputs
        run: |
          echo exists: ${{ steps.release_check.outputs.exists }}
          echo draft_exists: ${{ steps.release_check.outputs.draft_exists }}
          echo tag: ${{ steps.set_tag.outputs.tag }}

  skip-github-release:
    runs-on: ubuntu-latest
    needs: [check-release-exists]
    if: needs.check-release-exists.outputs.exists == 'true'

    steps:
      - name: Tag Exists, Skip GitHub Release Job
        run: echo A tag already exists for ${{ needs.check-release-exists.outputs.tag }} and commit, skipping release

  audit-release-different-commit:
    runs-on: ubuntu-latest
    needs: [check-release-exists]
    if: needs.check-release-exists.outputs.exists == 'false'

    steps:
      - name: Check if release already exists for commit
        uses: cardinalby/git-get-release-action@v1
        id: check_release_commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitSha: ${{inputs.sha}}
          doNotFailIfNotFound: true # returns blank outputs when not found instead of error
          searchLimit: 15 # Since we only care about recent releases, speed up the process

      - name: Print Release Details
        run: |
          echo steps.check_release_commit.outputs.id ${{ steps.check_release_commit.outputs.id}}
          echo steps.check_release_commit.outputs.tag_name ${{ steps.check_release_commit.outputs.tag_name}}
          echo steps.check_release_commit.outputs.target_commitish ${{ steps.check_release_commit.outputs.target_commitish}}
          echo steps.check_release_commit.outputs.prerelease ${{ steps.check_release_commit.outputs.prerelease}}

      # Since we already know a release for this tag does not exist, if we find anything it's for the wrong tag, exit
      - name: Check if the tag matches the version number
        if: steps.check_release_commit.outputs.id != ''
        run: |
          echo Tag "${{ steps.check_release_commit.outputs.tag_name}}" already exists for this commit!
          echo Cannot create a new tag for "${{ needs.check-release-exists.outputs.tag }}" for the same commit.
          exit 1

  github-release:
    runs-on: ubuntu-latest
    needs: [check-release-exists, audit-release-different-commit]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha }}

      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.version_number }}
          path: '.'

      - name: Display structure of all downloaded files
        run: ls -R

      - name: Set release type
        id: release_type
        run: |
          if ${{ contains(inputs.version_number, 'rc') ||  contains(inputs.version_number, 'b') }}
          then
            echo This is a prerelease
            echo ::set-output name=prerelease::--prerelease
          else
            echo This is not a prerelease
          fi

      - name: Set as draft release
        id: draft
        run: |
          if [[ ${{ inputs.testing }} == "true" ]]
          then
            echo This is a draft release
            echo ::set-output name=draft::--draft
          else
            echo This is not a draft release
          fi
      
      - name: Publish a release that was previously a draft
        if: ${{ inputs.testing }} == "false" && ${{ needs.check-release-exists.outputs.draft_exists }} == "true"
        run: |
          gh release edit $TAG --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.check-release-exists.outputs.tag }}

      - name: Create New GitHub Release
        if: ${{ needs.check-release-exists.outputs.draft_exists }} == 'false'
        run: |
          gh release create $TAG ./dist/* --title "$TITLE" --notes-file $RELEASE_NOTES --target $COMMIT $PRERELEASE $DRAFT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.check-release-exists.outputs.tag }}
          TITLE: ${{ github.event.repository.name }} ${{ needs.check-release-exists.outputs.tag }}
          RELEASE_NOTES: ${{ inputs.changelog_path }}
          COMMIT: ${{ inputs.sha }}
          PRERELEASE: ${{ steps.release_type.outputs.prerelease}}
          DRAFT: ${{ steps.draft.outputs.draft}}
