# **what?**
#
# Inputs:
#   
# **why?**
#
# **when?**
#

name: GitHub Release

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      version_number:
        required: true
        type: string
      file_uploads:
        description: Newline-delimited globs of paths to assets to upload for release
        required: true
        type: string

permissions:
  contents: write

jobs:
  log-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        run: |
            echo The last commit sha in the release: ${{ github.event.inputs.sha }}
            echo The release version number: ${{ github.event.inputs.version_number }}
            echo Expected Changlog path: "${{ github.workspace }}/${{ github.event.inputs.version_number }}.md"

  check-release-exists:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.set_existence.outputs.exists }}
  
    steps:
      - name: Placeholder
        run: echo Workflow is not built

      - uses: mukunku/tag-exists-action@v1.0.0
        # check if the tag already exists for this release.  If it does, the release has already been done
        # If there was a failure delete the tag and re-run
        id: checkTag
        with: 
          tag: v${{github.event.inputs.version_number}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
      - name: Check previous output
        run: echo steps.checkTag.outputs.exists ${{steps.checkTag.outputs.exists}}

      - name: Set output
        id: set_existence
        run: echo '::set-output name=exists::"${{steps.checkTag.outputs.exists}}"'

  github-release:
    runs-on: ubuntu-latest
    needs: [check-release-exists]
    if: ${{needs.check-release-exists.outputs.exists }} == 'false'
  
    steps:
      - name: Check previous output
        run: echo needs.check-release-exists.outputs.exists "${{needs.check-release-exists.outputs.exists }}"

      - uses: actions/download-artifact@v2
        with:
          name: ${{github.event.inputs.version_number}}
          path: '.'

      - name: List artifact contents (expect dist/ and <version>.md)
        run: ls -al

      # Need to set an output variable because env variables can't be taken as input
      # This is needed for the next step with releasing to GitHub
      - name: Find release type
        id: release_type
        env:
          IS_PRERELEASE: ${{ contains(github.event.inputs.version_number, 'rc') ||  contains(github.event.inputs.version_number, 'b') }}
        run: |
          echo ::set-output name=isPrerelease::$IS_PRERELEASE

      - name: Creating GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: dbt-core v${{github.event.inputs.version_number}}
          tag_name: v${{github.event.inputs.version_number}}
          prerelease: ${{ steps.release_type.outputs.isPrerelease }}
          target_commitish: ${{github.event.inputs.sha}}
          body_path: ${{ github.workspace }}/${{ github.event.inputs.version_number }}.md
          files: ${{ github.event.inputs.file_uploads }}
            # dbt_postgres-${{github.event.inputs.version_number}}-py3-none-any.whl
            # dbt_core-${{github.event.inputs.version_number}}-py3-none-any.whl
            # dbt-postgres-${{github.event.inputs.version_number}}.tar.gz
            # dbt-core-${{github.event.inputs.version_number}}.tar.gz