# **what?**
# After releasing to GitHub, release to Pypi
#
# Inputs:
#   tag - tag of release in the format v1.2.3rc1
#   testing - true is releasing to test pypi, otherwise false
# 
# **why?**
# Automate teh release process
#
# **when?**
#  After successfully releasing to GitHub
#

name: Pypi release

on:
  workflow_call:
    inputs:
      tag:
        description: 'The tag for the release (ie. v1.0.0b1)'
        required: true
        type: string
      testing:
        required: true
        type: boolean
    # pass through secrets for both PyPi Test and Prod so they're always there
    secrets:
      PYPI_API_TOKEN:
        description: AWS Access Key ID
        required: true
      TEST_PYPI_API_TOKEN:
        description: Test Pypi api token
        required: true

permissions:
  contents: read

jobs:
  log-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        run: |
            echo Tag: ${{ inputs.tag }}
            echo Release to test Pypi: ${{ inputs.testing }}

  check-pypi-exists:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.set_existence.outputs.exists }}
  
    steps:
      - name: Placeholder
        run: echo Workflow is not built
      - name: Set output
        id: set_existence
        run: echo '::set-output name=exists::false'

  skip-pypi-release:
    runs-on: ubuntu-latest
    needs: [check-pypi-exists]
    if: needs.check-pypi-exists.outputs.exists == 'true'

    steps:
      - name: Pypi Release Exists, Skip
        run: echo A release already exists for this version ${{ inputs.tag }} on Pypi, skipping

  pypi-release:
    needs: [check-pypi-exists]
    if: needs.check-pypi-exists.outputs.exists == 'false'
    runs-on: ubuntu-latest
  
    environment: PypiProd  # TODO: what's this? Could make be input for testing purposes?
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: 'dist'

      - name: Publish distribution to PyPI
        if: ${{ inputs.testing }} == 'true'
        uses: pypa/gh-action-pypi-publish@v1.5
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish distribution to test PyPI
        if: ${{ inputs.testing }} == 'false'
        uses: pypa/gh-action-pypi-publish@v1.5
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/