# **what?**
#
# Inputs:
#   
# **why?**
#
# **when?**
#

name: Pypi release

on:
  workflow_call:
    inputs:
      is_prod:
        default: false # https://packaging.python.org/en/latest/guides/using-testpypi/
    secrets:
      PYPI_API_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  check-pypi-exists:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.set_existence.outputs.exists }}
  
    steps:
      - name: Placeholder
        run: echo Workflow is not built
      - name: Set output
        id: set_existence
        run: echo '::set-output name=exists::"true"'

  pypi-release:
    if: jobs.check-pypi-exists.exists == 'false'
    runs-on: ubuntu-latest
  
    environment: PypiProd  # TODO: what's this? Could make be input for testing purposes?
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: 'dist'

      - name: Publish distribution to PyPI
        if: ${{ inputs.is_prod }} == 'true'
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish distribution to PyPI
        if: ${{ inputs.is_prod }} == 'false'
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/