# **what?**
#
# Inputs:
#   
# **why?**
#
# **when?**
#

name: Pypi release

on:
  workflow_call:
    inputs:
      is_prod:
        required: true
        type: boolean

permissions:
  contents: read

jobs:
  log-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        run: |
            echo Run for prod Pypi: ${{ github.event.inputs.is_prod }}

  check-pypi-exists:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.set_existence.outputs.exists }}
  
    steps:
      - name: Placeholder
        run: echo Workflow is not built
      - name: Set output
        id: set_existence
        run: echo '::set-output name=exists::false'

  pypi-release:
    needs: [check-pypi-exists]
    if: needs.check-pypi-exists.outputs.exists == false
    runs-on: ubuntu-latest
  
    environment: PypiProd  # TODO: what's this? Could make be input for testing purposes?
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: 'dist'

      - name: Publish distribution to PyPI
        if: ${{ inputs.is_prod }} == true
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish distribution to PyPI
        if: ${{ inputs.is_prod }} == false
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}  # TODO: document need for this secret
          repository_url: https://test.pypi.org/legacy/