name: "Version bump"
run-name: "Bump branch `${{ inputs.branch }}` to `${{ inputs.version }}`"

on:
    workflow_call:
        inputs:
            branch:
                description: "The branch to bump"
                type: string
                required: true
            version:
                description: "The version to bump to"
                type: string
                required: true
            bump-command:
                description: "The command to run to bump the version"
                type: string
                required: true
            working-directory:
                description: "The working directory, useful for monorepos"
                type: string
                default: "./"
        outputs:
            bumped:
                value: ${{ jobs.bump-version-inputs.outputs.current-version != inputs.version }}
                description: "Indicates if the version was bumped, or if it was skipped because it was already the current version"
                type: boolean

permissions: write-all

# only bump a branch/working-dir (package) to one version at a time
concurrency:
    group: "${{ github.workflow }}-${{ inputs.branch }}-${{ inputs.working-directory }}"
    cancel-in-progress: true

env:
  NOTIFICATION_PREFIX: "Bump version"

jobs:
    bump-version-inputs:
        name: "Inputs"
        runs-on: ubuntu-latest
        outputs:
            current-version: ${{ steps.current-version.outputs.version }}
        steps:
        -   name: "Check out `${{ inputs.branch }}`"
            uses: actions/checkout@v4
            with:
                ref: ${{ inputs.branch }}

        -   name: "Setup environment"
            uses: ./setup-environment

        -   name: "Set: current-version"
            id: current-version
            shell: bash
            run: echo "version=$(hatch version)" >> $GITHUB_OUTPUT
            working-directory: ${{ inputs.working-directory }}

        -   name: "[DEBUG] Inputs"
            run: |
                echo branch              : ${{ inputs.branch }}
                echo version             : ${{ inputs.version }}
                echo bump-command        : ${{ inputs.bump-command }}
                echo working-directory   : ${{ inputs.working-directory }}
                echo current-version     : ${{ steps.current-version.outputs.version }}

    bump-version:
        name: "Bump version"
        needs: bump-version-inputs
        if: ${{ needs.bump-version-inputs.outputs.current-version != inputs.version }}
        runs-on: ubuntu-latest
        steps:
        -   name: "Check out `${{ inputs.branch }}`"
            uses: actions/checkout@v4
            with:
              ref: ${{ inputs.branch }}

        -   name: "Setup environment"
            uses: ./setup-environment

        -   name: "Bump version to `${{ inputs.version }}`"
            shell: bash
            run: ${{ inputs.bump-command }}
            working-directory: ${{ inputs.working-directory }}

        -   name: "Commit and push changes"
            uses: ./github-commit
            with:
              message: "bump version to ${{ inputs.version }}"

        -   name: "[INFO] Bump version"
            shell: bash
            run: echo "::notice title=$TITLE::$MESSAGE"
            env:
                TITLE: "[${{ env.NOTIFICATION_PREFIX }}]: Bump version"
                MESSAGE: "Bumped `${{ inputs.branch }}` from `${{ needs.bump-version-inputs.outputs.current-version }}` to `${{ inputs.version }}`"

    skip-version-bump:
        name: "Skip version bump"
        needs: bump-version-inputs
        if: ${{ needs.bump-version-inputs.outputs.current-version == inputs.version }}
        runs-on: ubuntu-latest
        steps:
        -   name: "[INFO] Skipped version bump"
            shell: bash
            run: echo "::notice title=$TITLE::$MESSAGE"
            env:
                TITLE: "[${{ env.NOTIFICATION_PREFIX }}]: Skipped version bump"
                MESSAGE: "`${{ inputs.branch }}` is already at version `${{ inputs.version }}`"
