# **what?**
# Automates adding issues and PRs from Core repositories
# to the "Core management" project in GitHub.
#
# Inputs:
#   AUTHORIZATION_TOKEN: GitHub authorization token with sufficient scope

# **why?**
# Unfortunately, GitHub projects don't support this easily.
# We could add a workflow in each new project, or just run
# this every few hours.

# **when?**
# Every few hours, on PR, or manually.


name: core-project

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/3 * * *"
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/core-project.yml
      - scripts/core-project/**

jobs:
  add-items-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: pip installs
        run: pip install -r requirements.txt
        working-directory: scripts/core-project
      - name: run script
        run: python project.py
        working-directory: scripts/core-project
        env:
          FISHTOWN_BOT_PAT: ${{ secrets.FISHTOWN_BOT_PAT }}
 