# **what?**
# Cuts the `*.latest` branch, bumps dependencies on it, cleans up all files in `.changes/unreleased`
# and `.changes/previous verion on main and bumps main to the input version.

# **why?**
# Clean up the main branch after a release branch is cut and automate cutting the release branch.
# Generally reduces the workload of engineers and reducing error.

# **when?**
# This will run when called manually in a workflow.

# Example Usage including required permissions:  TODO: update once finalized

# permissions:
#   contents: read
#   pull-requests: write
#
# name: Cut Release Branch
# jobs:
#   changelog:
#     uses: dbt-labs/actions/.github/workflows/cut-release-branch.yml@main
#    with:
#      version_to_bump_main: 1.3.0a1
#      new_branch_name: 1.2.latest
#      repository: all
#    secrets: inherit # this is only acceptable because we own the action we're calling
#

# Note: This should be moved into the actions repos so it can be used in all adapters as well
# string together all updates into single action
# Should open PRs in all repos, do all adapters first then put link to all adapter PRs in the core PR talking about dependency
# add note to eventually commit changes directly and bypass checks - same as release - when we move to this model run test action after merge

name: Cut new release branch

on:
  workflow_dispatch:
    inputs:
      version_to_bump_main:
        description: 'The alpha version main should bump to (ex. 1.6.0a1)'
        required: true
      new_branch_name:
        description: 'The full name of the new branch (ex. 1.5.latest)'
        required: true

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  cut_branch:
    needs: ['prep_work']
    strategy:
      fail-fast: false
      matrix:
        repository: ['dbt-core', 'dbt-snwoflake', 'dbt-redshift', 'dbt-bigquery', 'dbt-spark']

    name: "Cut branch and clean up main for ${{ inputs.repository }}"
    uses: dbt-labs/actions/.github/workflows/cut-release-branch.yml@main
    with:
      version_to_bump_main: ${{ inputs.version_to_bump_main }}
      new_branch_name: ${{ inputs.new_branch_name }}
      repository: ${{ inputs.repository }}
    secrets:
      FISHTOWN_BOT_PAT: ${{ secrets.FISHTOWN_BOT_PAT }}
