# **what?**
# Calls mirroring Jira label Action. Includes adding a new label
# to an existing issue or removing a label as well

# **why?**
# Jira is our tool for tracking and we need to see these labels in there

# **when?**
# On labels being added or removed from issues

name: Jira Label Mirroring

on:
  issues:
    types: [labeled, unlabeled]
  workflow_call:
    secrets:
      JIRA_BASE_URL:
        required: true
      JIRA_USER_EMAIL:
        required: true
      JIRA_API_TOKEN:
        required: true

permissions:
  issues: read

jobs:
  call-label-action:
    uses: dbt-labs/actions/.github/workflows/jira-label.yml@main
    with:
      project_key: "CT"
    secrets:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
