# **what?**
# Transition a Jira issue to a new state
#
# Inputs:
#   project_key: the key used to prefix issue id in Jira (i.e. "CT" for issue CT-123)
#   JIRA_BASE_URL: your URL to Jira (i.e. https://abc.atlassian.net)
#   JIRA_USER_EMAIL: user email to log into Jira under
#   JIRA_API_TOKEN: user's API token

# **why?**
# Jira issues needs to reflect the state updates to issues in GitHub

# **when?**
# On GitHub Issue transitions (i.e. closed, reopened)

name: Jira Issue Transition

on:
  workflow_call:
    inputs:
      project_key:
        required: true
        type: string
    secrets:
      JIRA_BASE_URL:
        required: true
      JIRA_USER_EMAIL:
        required: true
      JIRA_API_TOKEN:
        required: true

jobs:
  extract-id:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, format('[{0}-', ${{inputs.project_key}}))
    outputs:
      issueId: ${{ steps.extract.outputs.issueId }}
    steps:
      - name: Extract Jira issue ID from title
        id: extract
        env:
          TITLE: "${{ github.event.issue.title }}"
        run: |
          issueId=$(echo -n $TITLE | awk '{print $1}' | awk -F'[][]' '{print $2}')
          echo "issueId=${issueId}" >> $GITHUB_STATE

  transition-issue:
    runs-on: ubuntu-latest
    needs: extract-id
    steps:
      - name: "[DEBUG] - Print Job Inputs"
        shell: bash
        id: echo_inputs
        run: |
          echo "all variables defined as ouputs in previous jobs"
          echo "Issue ID:            ${{ steps.extract.outputs.issueId }}"

      - name: Jira login
        uses: atlassian/gajira-login@master
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Transition issue in Jira to Done
        if: github.event.action == 'closed' || github.event.action == 'deleted'
        uses: atlassian/gajira-transition@master
        with:
          issue: "${{ steps.extract.outputs.issueId }}"
          transition: "Done"

      - name: Transition issue in Jira to To Do
        if: github.event.action == 'reopened'
        uses: atlassian/gajira-transition@master
        with:
          issue: "${{ steps.extract.outputs.issueId }}"
          transition: "Backlog"