name: Test Parse Semver Action

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**parse-semver**"

jobs:
  try-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Parse Semver
        id: parse-valid
        uses: ./parse-semver/
        with:
          version: "1.2.3rc4"

      - name: Parse Semver
        id: parse-invalid
        continue-on-error: true
        uses: ./parse-semver/
        with:
          version: "notaversion"

      - name: Test Valid Version
        run: |
          [ ${{ steps.parse-valid.outputs.major }} != 1 ] && exit 1
          [ ${{ steps.parse-valid.outputs.minor }} != 2 ] && exit 1
          [ ${{ steps.parse-valid.outputs.patch }} != 3 ] && exit 1
          [ ${{ steps.parse-valid.outputs.pre-release }} != rc4 ] && exit 1
          [ ${{ steps.parse-valid.outputs.pre-release-type }} != rc ] && exit 1
          [ ${{ steps.parse-valid.outputs.pre-release-version }} != 4 ] && exit 1
          [ ${{ steps.parse-valid.outputs.is-pre-release }} != 1 ] && exit 1
          exit 0

      - name: Test Invalid Version
        run: |
          [ ${{ steps.parse-invalid.conclusion }} != success ] && exit 1
          [ ${{ steps.parse-invalid.outcome }} != failure ] && exit 1
          exit 0
