# **what?**
# This workflow installs the latest version of dbt adapter from homebrew.
# It then runs 'dbt --version' to verify the installation was successful.
# If it fails for the scheduled runs, it will post to our team alerts channel.

# **why?**
# This is a simple way to test all adapter installations at a single
# time. It allows us to test them on a schedule as well to check for
# any breaking dependency changes that might happen and alert us on it.

# **when?**
# This reusable workflow can be called or started manually
# by specifying the package name

name: dbt Installation - Homebrew Integration Tests

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name to test (i.e. dbt-postgres)"
        required: true
        type: string
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        description: Slack app webhook url
        required: true

permissions:
  contents: read # required for slack-post-notification workflow

env:
  ARTIFACT_BASENAME: "homebrew-installation-test"
  ARTIFACT_RETENTION_DAYS: 1

defaults:
  run:
    shell: bash

jobs:
  homebrew-installation-test:
    runs-on: macos-12
    steps:
      - name: "Prepare Brew"
        # brew upgrade generates some symlink update warnings that cause failures without the || true.
        # They're just that the symlink wasn't updated which is okay to ignore.
        # This does cause other errors to be ignored but for this case that's safe since the brew install
        # step would likely fail at that point.
        run: brew update && brew upgrade || true

      - name: "[DEBUG] Show List Of Installed Homebrew Packages"
        run: brew list

      - name: "Tap dbt-labs/dbt Repository To Homebrew Formulae"
        run: brew tap dbt-labs/dbt

      - name: "[DEBUG] Show List Of All Currently Tapped Repositories"
        run: brew tap

      - name: "Brew Install ${{ inputs.package_name }}"
        run: brew install --verbose ${{ inputs.package_name }}

      - name: "Verify ${{ inputs.package_name }} Version"
        id: installation-test
        run: dbt --version

      - name: "[INFO] Homebrew installation test failure - GHA"
        if: ${{ always() && steps.installation-test.outcome != 'success' }}
        shell: bash
        run: |
          title="Homebrew installation test failure"
          message="Homebrew nightly installation test failed for ${{ inputs.package_name }}"
          echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"

      - name: "[INFO] Homebrew installation test failure - Slack"
        uses: ravsamhq/notify-slack-action@v2
        if: ${{ always() && steps.installation-test.outcome != 'success' && github.event_name == 'schedule' }}
        with:
          status: ${{ job.status }}
          notification_title: "Homebrew nightly installation test failed for ${{ inputs.package_name }}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}>"
          footer: "<{run_url}|View Run>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
