# **what?**
# This workflow pulls docker images with dbt adapters on board from GitHub Packages.
# Workflow pulls images with "1.*.latest" tags only.
# It then runs 'dbt --version' to verify the installation was successful.
# If it fails for the scheduled runs, it will post to our team alerts channel.

# **why?**
# This is a simple way to test all adapter installations at a single
# time. It allows us to test them on a schedule as well to check for
# any breaking dependency changes that might happen and alert us on it.

# **when?**
# This reusable workflow can be called or started manually
# by specifying the package name

name: dbt Installation - Docker Integration Tests

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name to test (i.e. dbt-postgres)"
        required: true
        type: string
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        description: Slack app webhook url
        required: true

permissions:
  contents: read # required for slack-post-notification workflow

env:
  GITHUB_PACKAGES_LINK: "ghcr.io"

jobs:
  docker-integration-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tag: ["1.1.latest", "1.2.latest", "1.3.latest"]

    steps:
      - name: "Resolve Image Ref"
        id: image-info
        run: |
          # Link example: ghcr.io/dbt-labs/dbt-bigquery:1.3.latest
          ref=${{ env.GITHUB_PACKAGES_LINK }}/dbt-labs/${{ inputs.package_name }}:${{ matrix.tag }}
          echo "ref=$ref" >> $GITHUB_OUTPUT

      - name: "[DEBUG] Show Docker Version"
        run: |
          docker version

      - name: "Pull Image - ${{ steps.image-info.outputs.ref }}"
        run: |
          docker pull ${{ steps.image-info.outputs.ref }}

      - name: "[DEBUG] Show Available Images"
        run: |
          docker image ls --all

      - name: "Verify ${{ inputs.package_name }} Version"
        uses: addnab/docker-run-action@v3
        with:
          registry: ${{ env.GITHUB_PACKAGES_LINK }}
          image: ${{ steps.image-info.outputs.ref }}
          run: dbt --version

  slack-notification:
    name: "Post Scheduled Run Failures"
    needs: docker-integration-test
    if: ${{ failure() && github.event_name == 'schedule' }}

    uses: dbt-labs/dbt-release/.github/workflows/slack-post-notification.yml@main
    with:
      status: "failure"
      notification_title: "Docker nightly integration test failed for - ${{ inputs.package_name }}"

    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
