# **what?**
# This workflow will take the new version number to bump to. With that
# it will run versionbump to update the version number everywhere in the
# code base and then run changie to create the corresponding changelog.
# A PR will be created with the changes that can be reviewed before committing.

# **why?**
# This is to aid in releasing dbt and making sure we have updated
# the version in all places and generated the changelog.

# **when?**
# This is triggered by a call in another workflow

name: Version Bump

on:
  workflow_call:
    inputs:
      version_number:
        description: "The version number to bump to (ex. 1.2.0, 1.3.0b1)"
        type: string
        required: true

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: "[DEBUG] Print Variables"
        run: |
          echo "all variables defined as inputs"
          echo The version_number: ${{ github.event.inputs.version_number }}

      - name: Check out the repository
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install spark dependencies
        if: (( github.repository == 'dbt-labs/dbt-spark' ))
        run: |
          sudo apt-get install libsasl2-dev

      - name: Install python dependencies
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install --upgrade pip

      - name: Add Homebrew to PATH
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Install Homebrew packages
        run: |
          brew install pre-commit
          brew tap miniscruff/changie https://github.com/miniscruff/changie
          brew install changie

      - name: Audit Version and Parse Into Parts
        id: semver
        uses: dbt-labs/actions/parse-semver@v1
        with:
          version: ${{ github.event.inputs.version_number }}

      - name: Set branch value
        id: variables
        run: |
          echo "BRANCH_NAME=prep-release/${{ github.event.inputs.version_number }}_$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

      - name: Create PR branch
        run: |
          git checkout -b ${{ steps.variables.outputs.BRANCH_NAME }}
          git push origin ${{ steps.variables.outputs.BRANCH_NAME }}
          git branch --set-upstream-to=origin/${{ steps.variables.outputs.BRANCH_NAME }} ${{ steps.variables.outputs.BRANCH_NAME }}

      - name: Bump version
        run: |
          source env/bin/activate
          pip install -r dev-requirements.txt
          env/bin/bumpversion --allow-dirty --new-version ${{ github.event.inputs.version_number }} major
          git status

      - name: Run changie
        run: |
          if [[ ${{ steps.semver.outputs.is-pre-release }} -eq 1 ]]
          then
            changie batch ${{ steps.semver.outputs.base-version }}  --move-dir '${{ steps.semver.outputs.base-version }}' --prerelease '${{ steps.semver.outputs.pre-release }}'
          else
            changie batch ${{ steps.semver.outputs.base-version }}  --include '${{ steps.semver.outputs.base-version }}' --remove-prereleases
          fi
          changie merge
          git status

      # this step will fail on whitespace errors but also correct them
      - name: Remove trailing whitespace
        continue-on-error: true
        run: |
          pre-commit run trailing-whitespace --files .bumpversion.cfg CHANGELOG.md .changes/*
          git status

      # this step will fail on newline errors but also correct them
      - name: Removing extra newlines
        continue-on-error: true
        run: |
          pre-commit run end-of-file-fixer --files .bumpversion.cfg CHANGELOG.md .changes/*
          git status

      - name: Commit version bump to branch
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "Github Build Bot"
          author_email: "buildbot@fishtownanalytics.com"
          message: "Bumping version to ${{ github.event.inputs.version_number }} and generate CHANGELOG"
          branch: "${{ steps.variables.outputs.BRANCH_NAME }}"
          push: "origin origin/${{ steps.variables.outputs.BRANCH_NAME }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          author: "Github Build Bot <buildbot@fishtownanalytics.com>"
          base: ${{github.ref}}
          title: "Bumping version to ${{ github.event.inputs.version_number }} and generate changelog"
          branch: "${{ steps.variables.outputs.BRANCH_NAME }}"
          labels: |
            Skip Changelog
